version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: starwars-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: starwars_db
      POSTGRES_USER: starwars_user
      POSTGRES_PASSWORD: starwars_password
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - starwars-network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: starwars-pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@starwars.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - '8080:80'
    depends_on:
      - postgres
    networks:
      - starwars-network

volumes:
  postgres_data:

networks:
  starwars-network:
    driver: bridge